### ISSUE TITLE
MultiVendorX vendor registration check box issues

### ISSUE THREAD

**Issue by tan-hue** [multivendorx/mvx#203]
Every option of the check boxes needs to be checked, no single option are accepted 
![image](https://user-images.githubusercontent.com/85879161/187210296-3ffee54a-0004-4349-a2ad-90db428d666a.png)

also in the admin dashboard, no extra information is shown i.e gender, phone number, company name after the registration process below task board option.

![image](https://user-images.githubusercontent.com/85879161/187211677-9baa84c1-5f62-472a-a5c4-f16151776c86.png)

**Comment by cool-raju** [comment]
For 1st  --- you may enable the required option on the backend registration setting. For the checkbox, if you have enabled the required option then you have to select all the options. 
For 2nd  --- as discussed only vendor name will be displayed on taskboard action. Because other fields are dynamic. Other fields are available in the vendor application section. 
@moumitahalder @tan-hue

**Comment by tan-hue** [comment]
The first issue got resolved but for the second one, the vendor's application section is not reflecting any extra details because the admin would like to see all the information before accepting or rejecting 

![image](https://user-images.githubusercontent.com/85879161/187218267-08face2d-63ef-41c0-ba4b-f303e9372d19.png)

**Comment by cool-raju** [comment]
The vendor application section will look like this https://www.loom.com/share/7da88bca8dbc45dbb8cc9fa520f54ddc
Please check again

**Comment by cool-raju** [comment]
@tan-hue

**Comment by cool-raju** [comment]
checked from elementor site

**Comment by tan-hue** [comment]
Thanks
