### ISSUE TITLE
QnA flow improvement 

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#378]
You can just give them a box to write their question down. At the same time answer Search should be available. Sometime we search with single word only and when we hit the ask the question button that one word gets submitted as the question which a vendor or admin cannot understand what they are asking for.
https://prnt.sc/4BGxeJHeuRxD

**Comment by Sangi0** [comment]
Show next to the name of the tab mvx_customer_qna_tab – the number of questions, so that the user can see that there are questions and clarifications there.

Now the name of the tab is: “Questions about the product”
It would be great to add a question counter: “Questions about the product (10)”


https://multivendorx.com/support-forum/topic/questions-about-the-product-tab-improving/#post-221185

**Comment by Sangi0** [comment]
The search function was not working correctly for the questions
