### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/mvx#658]
Deprecated: Creation of dynamic property MVX_Elementor_Module::$docs_types is deprecated in /var/www/vhosts/liberabile.it/httpdocs/wp-content/plugins/dc-woocommerce-multi-vendor/packages/mvx-elementor/includes/class-mvx-module.php on line 67

**Comment by Sangi0** [comment]
we haven't made any changes; the issue is consistently related to the PHP version. 

When reverting to PHP 7.4.33, the page functions correctly, instead if we switch to version 8.2.14, it returns that error. 

It's not a problem for us to stick with 7.4.33, but it's preferable to upgrade to PHP 8 for performance and security reasons.

--

Deprecated: Creation of dynamic property MVX_Elementor_Module::$docs_types is deprecated in /var/www/vhosts/liberabile.it/httpdocs/wp-content/plugins/dc-woocommerce-multi-vendor/packages/mvx-elementor/includes/class-mvx-module.php on line 67

Deprecated: strpos(): Passing null to parameter https://github.com/multivendorx/MultiVendorX/pull/1 ($haystack) of type string is deprecated in /var/www/vhosts/liberabile.it/httpdocs/wp-includes/functions.php on line 7241

Deprecated: str_replace(): Passing null to parameter https://github.com/multivendorx/MultiVendorX/pull/3 ($subject) of type array|string is deprecated in /var/www/vhosts/liberabile.it/httpdocs/wp-includes/functions.php on line 2187
