### ISSUE TITLE
Add filter for hiding certain categories

### ISSUE THREAD

**Issue by Sangi0** [multivendorx/mvx#830]
https://multivendorx.com/support-forum/topic/hide-category-for-vendor-when-adding-a-product/

**Comment by moumitahalder** [comment]
We’re trying to hide some product categories so that sellers are unable to select those to add their products in
We found the following code in your forums to do this:
We tried adding it as a snippet in a snippet plugin (our preffered way) and in functions.php of our theme but both didn’t work

add_filter( ‘mvx_vendor_product_classify_first_level_categories’, ‘mvx_vendor_product_cat_remove’);
function mvx_vendor_product_cat_remove($cat_array) {
$cat_array[‘exclude’] = array(15); // add category id here separated by comma
return $cat_array;
}

We changed the category ids to ours but it does not seem to hide it for the vendor when making a new product which means they’re still able to add a product in those categories

**Comment by Sangi0** [comment]
mvx_get_product_terms_product_cat_query_args this filter needs to added in the existing code
